
module.exports = {
  updatePage: 'updatepage',
  updateApp: 'updateapp',
  updateUser: 'updateuser',
  updateEventSubReady: 'updateeventsubready',
  addRedeem: 'addredeem',
  updateRedeem: 'updateredeem',
  allRedeems: 'allredeems',
  updateRewards: 'updaterewards',
  createReward: 'createreward',
  removeReward: 'removereward',
  editReward: 'editreward',
  updateRewardMap: 'updaterewardmap',
  setRewardToAction: 'setrewardtoaction',
  createRewardForAction: 'createrewardforaction',
  addPlayer: 'addplayer',
  updatePlayer: 'updateplayer',
  removePlayer: 'removeplayer',
  allPlayers: 'allplayers',
  updateDebugAutoRefund: 'updatedebugautorefund',
  addDebugPlayer: 'adddebugplayer',
  clearDebugPlayers: 'cleardebugplayers',
  requestBattle: 'requestbattle',
  startBattle: 'startbattle',
  cancelBattle: 'cancelbattle',
  updateBattle: 'updatebattle',
  updateBattleQueue: 'updatebattlequeue',
  finishBattle: 'finishBattle',
  updateBattleResults: 'updateBattleResults',
  updateBotReady: 'updatebotready'
};
